apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
  namespace: ckad-chapter2
spec:
  containers:
  - image: nginx
    name: mypod
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    ports:
    - containerPort: 80
    resources: {}
  volumes:
  - name: config-volume
    configMap:
      name: backend-config
  restartPolicy: Never
  dnsPolicy: ClusterFirst
status: {}
