apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
  namespace: ckad-chapter2
spec:
  containers:
  - image: nginx
    name: mypod
    envFrom:
    - configMapRef:
        name: backend-config
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
