apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: ckad-chapter2
spec:
  containers:
  - image: nginx
    name: pod
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret-volume
      mountPath: /var/app
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
