apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysecretpod
  name: mysecretpod
  namespace: ckad-chapter2
spec:
  containers:
  - image: nginx
    name: mysecretpod
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-creds
          key: pwd
    ports:
    - containerPort: 80
